// Generated by CoffeeScript 1.6.3
var PmwServoDriver, pwm, servoMax, servoMin, setServoPulse, sleep;

PmwServoDriver = require("../main");

sleep = require('sleep');

pwm = new PmwServoDriver(0x40, '/dev/i2c-1', true);

servoMin = 150;

servoMax = 600;

setServoPulse = function(channel, pulse) {
  var pulseLength;
  pulseLength = 1000000;
  pulseLength /= 60;
  print("%d us per period" % pulseLength);
  pulseLength /= 4096;
  print("%d us per bit" % pulseLength);
  pulse *= 1000;
  pulse /= pulseLength;
  return pwm.setPWM(channel, 0, pulse);
};

pwm.setPWMFreq(60);

pwm.scan();

while (true) {
  pwm.setPWM(0, 0, servoMin);
  sleep.sleep(1);
  pwm.setPWM(0, 0, servoMax);
  sleep.sleep(1);
}
